### ISSUE TITLE
Error: test_basic_object_does_not_throw_exception(TestWeakReference)

### ISSUE THREAD

**Issue by ghost** [ruby-concurrency/ref#10]
I am trying to upgrade ruby-ref for debian. A test fails and it seems to be included new, i don't see it in the file test/weak_reference_test.rb in version ref-1.0.2

Started
.............E
===============================================================================
Error: test_basic_object_does_not_throw_exception(TestWeakReference)
  NoMethodError: undefined method `respond_to?' for #<BasicObject:0x8960750>
/home/molloy/Build/Temp/upgrade-ruby-ref/ruby-ref/test/weak_reference_test.rb:51:in `test_basic_object_does_not_throw_exception'
     48:     def test_basic_object_does_not_throw_exception
     49:       obj = BasicObject.new
     50:       ref = Ref::WeakReference.new(obj)
  => 51:       assert_equal obj, ref.object
     52:     end
     53:   end
     54: end
===============================================================================
.........................................

Thanks.

**Comment by jdantonio** [comment]
This was fixed in PR #15.
