### ISSUE TITLE
rescue RuntimeError in Maps for define_finalizer on frozen object

### ISSUE THREAD

**Issue by jemc** [ruby-concurrency/ref#12]
```
pry(main)> Ref::WeakKeyMap.new[:test] = 88
RuntimeError: can't modify frozen Symbol
```

I'm not sure if the maintainer will agree with the spirit of this request, but I'm trying to maintain a WeakKeyMap that operates with arbitrary objects (any hashable object).  I want it to be managed (garbage collected) like a WeakKeyMap.  That is, when any of the key objects get garbage collected, the key value pair will get garbage collected.  Obviously, symbols will never get garbage collected, and those key value pairs will never be removed, but this is the desired behaviour.

Right now, I'm subclassing WeakKeyMap to get the job done for my application, but I'd rather try to get this integrated upstream if possible.  My solution currently transforms the define_finalizer line like this:
```
ObjectSpace.define_finalizer(key, @reference_cleanup)
```
```
begin; ObjectSpace.define_finalizer(key, @reference_cleanup)
rescue RuntimeError; end
```

If the maintainer is amenable to this type of change, I'll take the time to submit a pull request, complete with matching tests.

If this kind of change were pulled in, I'd be able to make a mixed weak and strong key map with the following code in my application:

```ruby
    class Map < Ref::AbstractReferenceKeyMap
      @@_router_map_lock = Mutex.new
      
      def []=(key, value)
        @@_router_map_lock.synchronize do
          self.class.reference_class = \
            key.frozen? ? Ref::StrongReference : Ref::WeakReference
          super
        end
      end
    end
```

Although this locked access to the class method is still weird, and it may be little too tightly coupled to this library to be truly happy wth in the long run, as I'm not sure if self.reference_class is public api?  Let me know if you have any ideas for this implementation.

**Comment by jdantonio** [comment]
@jemc Are you still interested in exploring this functionality? The original maintainer recently agreed to transfer this gem to the `ruby-concurrency` org and allow us to help him maintain it (we wanted to use `Ref::WeakKeyMap` in `concurrent-ruby`). It's been a long time since you created this issue so I'll understand if you've moved on to other projects. If you're still interested I'd love to discuss this further otherwise I'd like to close the issue.

**Comment by jemc** [comment]
@jdantonio 
As you guessed, my use case has dissolved at this point - I took the other project in a different direction.  Best of luck with maintaining this gem!
