### ISSUE TITLE
Please update HISTORY.txt

### ISSUE THREAD

**Issue by PikachuEXE** [ruby-concurrency/ref#35]
Since there is a major version bump
It's hard to know what's changed by reading commits

**Comment by toncid** [comment]
:+1:

**Comment by jdantonio** [comment]
I apologize for not doing that already. I will update it this week.

This release has virtually no functional changes. It's mostly an "under new management" release. The original author had lost interested in maintaining the gem and was kind enough to let us take over. I decided to make this release 2.0 in case we broke anything. The 1.x line is still purely the original author's work.

For the 2.0 release we removed support for MRI 1.8, removed the IronRuby-specific optimizations, and migrated the test suite to RSpec (concurrent-ruby uses RSpec so we opted for consistency). The only functional change is that we added a few methods (`#to_h` and `#merge`) to the weak key map classes (see PR #34). This was purely an additive change.

**Comment by jdantonio** [comment]
Done!

**Comment by PikachuEXE** [comment]
Thanks for the update!

**Comment by toncid** [comment]
Thanks!
