### ISSUE TITLE
Seg fault on MRI 1.9.3

### ISSUE THREAD

**Issue by arkadiyt** [ruby-concurrency/ref#5]
We had a segmentation fault originating from the ref gem:

$ ruby -v
ruby 1.9.3p125 (2012-02-16 revision 34643) [x86_64-linux]

$ cat /proc/version
Linux version 3.2.0-23-virtual (buildd@crested) (gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu4) ) #36-Ubuntu SMP Tue Apr 10 22:29:03 UTC 2012

Seg fault output:
https://gist.github.com/arkadiyt/73824d1251ce5c106822

I believe this is a bug with the interpeter but thought I'd create this issue as well to see if there's something that the ref gem can do to avoid this

**Comment by jdantonio** [comment]
Give the age of the issue, the upcoming [end-of-life of MRI 1.9.3](https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/), the missing gist, and the documentation indicating that `WeakReference` does not work on 1.9.3, I'm closing this issue.

Should this seg fault arise again, please open a new issue and we'll look into it ASAP.
